dataset:
  target: dataset.licdataset_with_bg_and_text.LICDatasetWithBGAndText
  params:
    file_list: ./datalists/train_with_bg_and_text.list
    out_size: 256
    crop_type: random
    use_hflip: True
    use_rot: False
    use_colorjitter: True

data_loader:
  batch_size: 1
  shuffle: true
  num_workers: 8
  drop_last: true

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform